name: bare-pyzmq

on:
  push:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash
env:
  PYTHONFAULTHANDLER: "1"

jobs:
  test-pyzmq:
    name: ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.13"
            os: ubuntu-latest
          - python-version: "3.14"
            os: ubuntu-latest
          - python-version: "3.13"
            os: windows-latest
          - python-version: "3.14"
            os: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: install
      run: |
        python -m pip install uv
        python -m uv pip install pyzmq pytest nbclient ipykernel .
    - name: test
      run: |
        export PYTHONWARNINGS=d
        python ./test.py
        python -m pytest -vvsx ./test.py
        # python -m pytest -vvsx ./tests/test_notebook.py
